// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QwWCPnL9ENFZ3j-AjxUrokI9tsPetxI',
    appId: '1:353013621078:web:121db94ba59837f3d4b6f7',
    messagingSenderId: '353013621078',
    projectId: 'mobile-exams-414a2',
    authDomain: 'mobile-exams-414a2.firebaseapp.com',
    storageBucket: 'mobile-exams-414a2.firebasestorage.app',
    measurementId: 'G-CVCEZ3G0RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVKB2tNHM5nff803jpkTbFPfNY20vs_qE',
    appId: '1:353013621078:android:19a144630831989ad4b6f7',
    messagingSenderId: '353013621078',
    projectId: 'mobile-exams-414a2',
    storageBucket: 'mobile-exams-414a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoNTiafyhF30AQcOgqtrzSiMCezClQ5IA',
    appId: '1:353013621078:ios:4085e2f8a142905cd4b6f7',
    messagingSenderId: '353013621078',
    projectId: 'mobile-exams-414a2',
    storageBucket: 'mobile-exams-414a2.firebasestorage.app',
    iosBundleId: 'com.example.mobileExam',
  );
}
